spring.application.name=CareerTrack

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5434/careertrack
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Server
server.port=8080